pom.xml
=> Jakarta spec fixes

.gitignore, pom.xml, src/main/java/javax/security/jacc/EJBMethodPermission.java, src/main/java/javax/security/jacc/EJBRoleRefPermission.java, src/main/java/javax/security/jacc/HttpMethodSpec.java, src/main/java/javax/security/jacc/PolicyConfiguration.java, src/main/java/javax/security/jacc/PolicyConfigurationFactory.java, src/main/java/javax/security/jacc/PolicyContext.java, src/main/java/javax/security/jacc/PolicyContextException.java, src/main/java/javax/security/jacc/PolicyContextHandler.java, src/main/java/javax/security/jacc/URLPattern.java, src/main/java/javax/security/jacc/URLPatternSpec.java, src/main/java/javax/security/jacc/WebResourcePermission.java, src/main/java/javax/security/jacc/WebRoleRefPermission.java, src/main/java/javax/security/jacc/WebUserDataPermission.java
Merges cleanup and spec fixes from master branch
=> Clean up ee4j

pom.xml
Update to point to staged jakarta artifacts
Signed-off-by: Vinay Vishal <vinay.vishal@oracle.com>
=> Update api dependency details

pom.xml
=> Removed redundant comment, fixed spec version, LICENSE/NOTICE META-INF

src/main/java/javax/security/jacc/PolicyContext.java
=> Restored signature

pom.xml
=> Manual merge EE4J_8 into master

CONTRIBUTING.md, NOTICE.md, pom.xml, src/main/java/javax/security/jacc/PolicyConfigurationFactory.java
=> #25 Change project name to Jakarta Authorization

src/main/java/javax/security/jacc/EJBMethodPermission.java, src/main/java/javax/security/jacc/EJBRoleRefPermission.java, src/main/java/javax/security/jacc/URLPattern.java, src/main/java/javax/security/jacc/URLPatternSpec.java, src/main/java/javax/security/jacc/WebResourcePermission.java, src/main/java/javax/security/jacc/WebRoleRefPermission.java, src/main/java/javax/security/jacc/WebUserDataPermission.java, src/main/java/javax/security/jacc/package.html, src/main/resources/exclude-common.xml
#30 Update references to other specifications with their new names
Updated EJB and Servlet references
=> #30 Update references to other specs

pom.xml
=> Set Java versions explicitly to 1.8

pom.xml
=> Update name and description to align with Eclipse name and scope

README.md
=> Add readme to project

api/pom.xml, pom.xml, spec/pom.xml
=>  Prepare for 1.6.2 release

api/pom.xml
=> Update to Jakarta Servlet 4.0.3

api/pom.xml, pom.xml, spec/src/main/asciidoc/scope.adoc
=> Updated scope statement to remove hyphen and be consistent.

spec/src/main/asciidoc/license-efsl.adoc
=> Updated copyright

api/pom.xml, api/src/main/javadoc/doc-files/speclicense.html
=> Updated Javadoc for latest Jakarta EE 8 requirements

spec/src/main/asciidoc/authorization-spec.adoc
=> Update doctitle by removing version number

api/pom.xml, pom.xml, spec/pom.xml
New: jakarta.authorization:jakarta.authorization-api:1.5.0
See: https://github.com/jakartaee/specifications/pull/54#issuecomment-521897765
=> Changed over Maven coordinates

api/src/main/java/javax/security/jacc/PolicyContext.java
=> Fix signature for Jakarta EE 8 TCK

api/pom.xml
=> Merge final release branch 1.5.0

spec/src/main/asciidoc/chapters/2_provider-configuration.adoc
=> #58 Cleaned chapter 2 - provider configuration

spec/src/main/asciidoc/chapters/3_policy-configuration.adoc
=> #58 Cleaned chapter 3 - policy configuration

spec/pom.xml
=> Update asciidoc to 1.5.0

api/pom.xml
=> #58 Prepare for RC1 release

spec/src/main/asciidoc/chapters/4_policy-decision.adoc
=> Cleaned chapter 4 - policy decision

spec/src/main/asciidoc/chapters/a_related-documents.adoc
=> Cleaned Appendix A - related documents

spec/src/main/asciidoc/chapters/b_issues.adoc
=> #58 Cleaned appendix b - issues

spec/src/main/asciidoc/chapters/c_revision-history.adoc
=> #58 Cleaned appendix c - revision history

spec/src/main/asciidoc/chapters/1_overview.adoc, spec/src/main/asciidoc/chapters/3_policy-configuration.adoc
=> #58 Updated references

spec/src/main/asciidoc/chapters/2_provider-configuration.adoc, spec/src/main/asciidoc/chapters/c_revision-history.adoc
=> #58 Removed unused references

CONTRIBUTING.md, NOTICE.md, api/pom.xml, pom.xml
Just to save redirect on github.
=> Use direct links to github (559843)

api/pom.xml, spec/pom.xml
=> Version to snapshot, removed unneeded plugin, updated versions

api/pom.xml, pom.xml, spec/pom.xml
=> Updated poms - versions, automatic module and parent id

spec/src/main/asciidoc/chapters/4_policy-decision.adoc
=> #80 Jakarta-ize Policy Context Handler property keys

api/src/main/javadoc/doc-files/speclicense.html, spec/src/main/asciidoc/license-efsl.adoc
=> #77 Update EFSL for Specifications and Javadoc

api/pom.xml
=> Update javadoc copyright

api/src/main/java/jakarta/security/jacc/PolicyConfigurationFactory.java
This is a follow up of the following PR https://github.com/eclipse-ee4j/authorization/pull/49
=> Resolves #48 Ensure only one PolicyConfigurationFactory will be instantiated.

spec/src/main/asciidoc/preface.adoc
Signed-off-by: Jean-Louis Monteiro <jlmonteiro@tomitribe.com>
=> Jakarta branding and version missmatch in preface

api/pom.xml
=> Merge 2.0.0 into master

api/pom.xml, pom.xml, spec/pom.xml
=> Main version to 2.1, java to 11, update of plugins, copyright 2021

api/pom.xml, api/src/main/java/module-info.java
See https://github.com/jakartaee/specification-committee/blob/master/names.adoc
=> Add module-info according to Jakarta EE 10 plan

api/src/main/java/jakarta/security/jacc/PolicyContext.java
=> Tabs to spaces in one file

api/src/main/java/jakarta/security/jacc/PolicyConfigurationFactory.java
=> #53 Add getPolicyConfiguration methods without state requirement

api/src/main/java/jakarta/security/jacc/PolicyConfiguration.java
=> #52 Add methods to PolicyConfiguation to read permissions

api/src/main/java/jakarta/security/jacc/PolicyContext.java
=> #105 Generic return value for getContext

api/pom.xml, pom.xml, spec/pom.xml
=> Update versions in pom and copyright years

spec/src/main/asciidoc/authorization-spec.adoc
=> Updated project Eclipse project link

api/pom.xml, api/src/main/java/jakarta/security/jacc/PolicyConfiguration.java, api/src/main/java/jakarta/security/jacc/PolicyConfigurationFactory.java
=> Fix javadoc warnings and update compiler plugin

api/pom.xml, pom.xml, spec/pom.xml
=> Update versions in pom

spec/src/main/asciidoc/authorization-spec.adoc, spec/src/main/asciidoc/license-efsl.adoc
=> Updating copyright year

api/pom.xml, pom.xml, spec/pom.xml
Update pom versions and copyright
=> Next version is 3.0

api/src/main/java/jakarta/security/jacc/PolicyConfiguration.java, api/src/main/java/jakarta/security/jacc/PolicyConfigurationFactory.java, api/src/main/java/jakarta/security/jacc/PolicyContext.java
As per the Jakarta EE 11 plan: https://jakarta.ee/specifications/platform/11/
=> Remove usages of SecurityManager in API as per #126

api/src/main/java/jakarta/security/jacc/Policy.java, api/src/main/java/jakarta/security/jacc/PolicyFactory.java
Draft PR intended for the M1 release.
=> Policy replacement as per #99

api/src/main/java/jakarta/security/jacc/PolicyContext.java
=> Add missing generic #128

api/src/main/java/jakarta/security/jacc/PrincipalMapper.java
=> Add principal mapper interface per #133

api/src/main/java/jakarta/security/jacc/PolicyConfiguration.java
=> Add default methods to PolicyConfiguration as per #134

api/src/main/java/jakarta/security/jacc/PolicyConfigurationFactory.java, api/src/main/java/jakarta/security/jacc/PolicyContext.java
=> Add constants for various keys as per #135

spec/pom.xml, spec/src/main/asciidoc/authorization-spec.adoc, spec/src/main/asciidoc/chapters/1_overview.adoc, spec/src/main/asciidoc/chapters/2_provider-configuration.adoc, spec/src/main/asciidoc/chapters/3_policy-configuration.adoc, spec/src/main/asciidoc/chapters/4_policy-decision.adoc, spec/src/main/asciidoc/chapters/5_legacy_support.adoc, spec/src/main/asciidoc/chapters/a_related-documents.adoc, spec/src/main/asciidoc/chapters/c_revision-history.adoc, spec/src/main/asciidoc/preface.adoc
Mostly to address removal of security manager, some updates regarding enhances or changes in 3.0.
=> Update spec text for 3.0 release

api/src/main/java/jakarta/security/jacc/PolicyConfigurationFactory.java, api/src/main/java/jakarta/security/jacc/PolicyFactory.java, spec/src/main/asciidoc/chapters/2_provider-configuration.adoc, tck/app-custom-trace-policyconfiguration/src/main/java/ee/jakarta/tck/authorization/test/TSPolicyConfigurationFactoryImpl.java, tck/app-custom-trace-policyconfiguration/src/main/java/ee/jakarta/tck/authorization/test/TSPolicyConfigurationImpl.java, tck/app-custom-trace-policyconfigurationfactory/src/main/java/ee/jakarta/tck/authorization/test/TSPolicyConfigurationFactoryImpl.java
Update API, spec text and TCK.
=> Add wrapping constructors to factories for #156

api/src/main/java/jakarta/security/jacc/Policy.java, api/src/main/java/jakarta/security/jacc/PolicyFactory.java, api/src/main/java/jakarta/security/jacc/PrincipalMapper.java, spec/src/main/asciidoc/chapters/2_provider-configuration.adoc, tck/app-custom-policyfactory/pom.xml, tck/app-custom-policyfactory/src/main/java/ee/jakarta/tck/authorization/test/ProtectedServlet.java, tck/app-custom-policyfactory/src/main/java/ee/jakarta/tck/authorization/test/TestPolicy.java, tck/app-custom-policyfactory/src/main/java/ee/jakarta/tck/authorization/test/TestPolicyFactory.java, tck/app-custom-policyfactory/src/main/webapp/WEB-INF/beans.xml, tck/app-custom-policyfactory/src/main/webapp/WEB-INF/web.xml, tck/app-custom-policyfactory/src/test/java/ee/jakarta/tck/authorization/test/AppCustomPolicyFactoryIT.java, tck/pom.xml
=> Specify and add TCK test for wrapping constructor for PolicyFactory
